### ISSUE TITLE
关于计分算法的建议

### ISSUE THREAD

**Issue by gengjie88** [real-web-world/hh-lol-prophet#1]
💪star支持

_**不同的人对于每个玩家表现会有不同的看法**_
对于不同的位置不同的英雄可以有更加精细的算法,一下是我的看法

1. **辅助**:参团率,视野评分
2. **ad**:伤害转化率,战损
3. **中单**:伤害转化率,参团率,战损
4. **打野**:参团率,视野评分
5. **上单**:基本不玩

**Comment by buffge** [comment]
已加入计划 "对特定位置 计算特定指标"

**Comment by Alone-2** [comment]
存在换位置的情况怎么办

**Comment by buffge** [comment]
> 存在换位置的情况怎么办
这个我已经考虑到了, 我的想法是给英雄和技能加权值 比如 带传送了我就判断他一定不是辅助,带cj
了就一定是打野(除非他的位置是上单并且是凤女 扇子妈)
先拿服务器告诉我的位置,然后判断英雄和带的召唤师技能.
现在内测先以系统的为准

**Comment by gengjie88** [comment]
可以把postman接口导出一份给我吗?我想看看能拿到什么数据

**Comment by SilverNight7350** [comment]
借楼说一下，不知道能否在接口里面发现该局排位是单双排还是灵活组排，计算得分的时候感觉只计算对应的排位模式的分数比较好。意思就是打开单双排时，只会去计算队友单双排的KDA，而不是将大乱斗，灵活组排的KDA一起算进来。

**Comment by buffge** [comment]
> 借楼说一下，不知道能否在接口里面发现该局排位是单双排还是灵活组排，计算得分的时候感觉只计算对应的排位模式的分数比较好。意思就是打开单双排时，只会去计算队友单双排的KDA，而不是将大乱斗，灵活组排的KDA一起算进来。
现在是计算 匹配 单双排 组排 大乱斗 kda. 其实打其他模式强的 打排位也强 马上准备改版了 就用wegame的计分方式

**Comment by buffge** [comment]
> 可以把postman接口导出一份给我吗?我想看看能拿到什么数据

你自己搜下,网上全是. 我不能传播这个json,因为里面有的接口能让人做坏事. 我传播了 我怕马哥找我麻烦. 如果要这个软件相关的接口
去 services/lcu/api.go 这里看,都有注释

**Comment by SilverNight7350** [comment]
> > 借楼说一下，不知道能否在接口里面发现该局排位是单双排还是灵活组排，计算得分的时候感觉只计算对应的排位模式的分数比较好。意思就是打开单双排时，只会去计算队友单双排的KDA，而不是将大乱斗，灵活组排的KDA一起算进来。
> > 现在是计算 匹配 单双排 组排 大乱斗 kda. 其实打其他模式强的 打排位也强 马上准备改版了 就用wegame的计分方式

emmm，打其他模式的强的人确实打排位也不差，但是还有种情况是应该由不少人会在灵活排位和大乱斗里面瞎玩，练英雄之类的，只会在单双排里面玩的非常认真。这种情况下，评分就会出现一些局限性了。

**Comment by buffge** [comment]
> > > 借楼说一下，不知道能否在接口里面发现该局排位是单双排还是灵活组排，计算得分的时候感觉只计算对应的排位模式的分数比较好。意思就是打开单双排时，只会去计算队友单双排的KDA，而不是将大乱斗，灵活组排的KDA一起算进来。
> > > 现在是计算 匹配 单双排 组排 大乱斗 kda. 其实打其他模式强的 打排位也强 马上准备改版了 就用wegame的计分方式
> 
> emmm，打其他模式的强的人确实打排位也不差，但是还有种情况是应该由不少人会在灵活排位和大乱斗里面瞎玩，练英雄之类的，只会在单双排里面玩的非常认真。这种情况下，评分就会出现一些局限性了。

会加入选择 游戏模式作为评分标准 配置选项. 优先级不高,但肯定会做
