### ISSUE TITLE
队友看不到完整的记录

### ISSUE THREAD

**Issue by lulufeiacount** [real-web-world/hh-lol-prophet#16]
不知道是不是发送间隔太短了，队友经常看不到所有的记录，一次性发送5条，偶尔队友只能看见一条评分呢

**Comment by kb121** [comment]
我队友也经常看不到所有马匹记录

**Comment by buffge** [comment]
我阳性了被隔离到方仓了，等我回来后我测试下让所有人都看到

**Comment by lulufeiacount** [comment]
> 我阳性了被隔离到方仓了，等我回来后我测试下让所有人都看到

老哥，加油

**Comment by kb121** [comment]
> 我阳性了被隔离到方仓了，等我回来后我测试下让所有人都看到

老哥，加油

**Comment by Cloudx-code** [comment]
好像目前在一区和黑色玫瑰可以正常使用，访问别的区，比如“卡拉曼达”会出现404

**Comment by buffge** [comment]
等tx开放战绩查询接口再更新
