### ISSUE TITLE
排位赛进入游戏后，不能自动发送马匹信息到聊天框！

### ISSUE THREAD

**Issue by quqingfei** [real-web-world/hh-lol-prophet#17]
我进入游戏后，聊天框没有自动发送敌方马匹信息！可否有按钮能实现**再次发送敌方马匹信息**这个功能？
有些被禁言的玩家，每局只有5句话能讲。
希望有个按钮能控制 **是否对局开始后发送敌方马匹信息**！

**Comment by buffge** [comment]
等下个版本做，我目前被隔离在方仓

**Comment by stackAttackcp** [comment]
老哥你这个用什么语言实现的？用到了哪些技术呀？

**Comment by quqingfei** [comment]
> 老哥你这个用什么语言实现的？用到了哪些技术呀？

**Comment by xxxshalxd** [comment]
> 老哥你这个用什么语言实现的？用到了哪些技术呀？

外面不是写了用go的么？0.0

**Comment by jun0315** [comment]
> 等下个版本做，我目前被隔离在方仓

加油！注意安全

**Comment by buffge** [comment]
等tx开放战绩查询接口再更新
