### ISSUE TITLE
有兴趣讲一下原理吗

### ISSUE THREAD

**Issue by ET-stack** [real-web-world/hh-lol-prophet#18]
目前，我对go语法不太熟悉， 我用的是Java，但是我也想实现类似的功能，我是想重造轮子，

**Comment by buffge** [comment]
没有原理，就是腾讯开放了几个api 随便用什么语言用http协议调这个接口都能实现

**Comment by ET-stack** [comment]
那请问一下，这几个api接口，在项目里吗，我能直接使用么，

**Comment by LiJoeAllen** [comment]
> 没有几个原理，就是腾讯开放了api 随便用什么用http协议调这个接口可以实现
是这个吗？
https://developer.riotgames.com/docs/lol#game-client-api_live-client-data-api

**Comment by ET-stack** [comment]
应该是的，好的我看看，谢谢

**Comment by LiJoeAllen** [comment]
应该啥呀，大哥没说是，看了代码，从进程中读出来的那部分是重点
