### ISSUE TITLE
不能自动发送

### ISSUE THREAD

**Issue by xioyodd** [real-web-world/hh-lol-prophet#21]
{"level":"info","ts":"2022-04-22T21:49:33.754+0800","caller":"lcu/api.go:813","msg":"获取当前对局聊天组失败","error":"json: cannot unmarshal object into Go value of type []lcu.Conversation"}

**Comment by fmy-fly** [comment]
0800","caller":"lcu/api.go:813","msg":"获取当前对局聊天组失败","error":"json: cannot unmarshal object into Go value of type []lcu.Conversation"}

**Comment by buffge** [comment]
等tx开放战绩查询接口再更新
