### ISSUE TITLE
Feature request: add support for lolskin

### ISSUE THREAD

**Issue by BSDxxxx** [real-web-world/hh-lol-prophet#23]
http://leagueskin.net/

**Comment by buffge** [comment]
违法工具不做. 建议玩家自己找个郊区 打个钻1 再去峡谷 会送30w点券. 打上峡谷后 哪怕你原来的区不是钻1了 只要峡谷一直在玩就会一直有峡谷资格.  峡谷每周赢10局会送1w点券
