### ISSUE TITLE
源码运行问题

### ISSUE THREAD

**Issue by Ada0317** [real-web-world/hh-lol-prophet#26]
新手提问，程序源码是从哪个入口文件执行的？

**Comment by Ada0317** [comment]
问题已解决，hh-lol-prephet目录下的main函数，因为我自己编译生成exe可执行文件的时候报了一个gcc有关的错误，我装了一下TDM-GCC然后重启电脑之后就可以编译运行成功了，继续学习

**Comment by buffge** [comment]
> 



> 问题已解决，hh-lol-prephet目录下的main函数，因为我自己编译生成exe可执行文件的时候报了一个gcc有关的错误，我装了一下TDM-GCC然后重启电脑之后就可以编译运行成功了，继续学习

这个不依赖c
