### ISSUE TITLE
命令行参数中 `riotclient-app-port` 和 `--app-port` 两个端口代表的 `api` 有什么区别

### ISSUE THREAD

**Issue by arrebole** [real-web-world/hh-lol-prophet#27]
猜想可能是有两个后端，尝试过在 `riotclient-app-port` 指定的端口中可以访问 `/swagger/v3/openapi.json` 查看接口文档

**Comment by arrebole** [comment]
https://developer.riotgames.com/docs/lol#game-client-api_live-client-data-api 这份文档指向的应该是 `riotclient-app-port` 指向的服务

**Comment by arrebole** [comment]
但是看本项目使用的是 `--app-port` 指向的服务

**Comment by buffge** [comment]
当时找到这端口能跑就行 其他的参数没研究
