### ISSUE TITLE
可以增加个按键把信息发送到游戏开始后的聊天框吗

### ISSUE THREAD

**Issue by corvofeng** [real-web-world/hh-lol-prophet#3]
我比较菜, 玩匹配多, 选人的时候不会太关注对面队友,  开始之后可能会在聊天框看一下, 希望作者能实现看看, 也不白嫖了, 实现的话请你咖啡吧

**Comment by buffge** [comment]
可能会封号,并且我是开源的,我怕马哥找我,其他都是他开放的接口,这个对局发言不是的,万一现在是进入对局后显示在控制台,并且复制到剪切板了.

**Comment by buffge** [comment]
目前已经发消息给tx lol插件管理员了,我看了一下发消息时橙色风险,应该不违法,如果违法就去掉,tx一周不回复我就把这个功能加进去,默认关闭

**Comment by githik999** [comment]
> 目前已经发消息给tx lol插件管理员了,我看了一下发消息时橙色风险,应该不违法,如果违法就去掉,tx一周不回复我就把这个功能加进去,默认关闭

大佬这个对局内发送消息的代码 大概在什么地方 我找了一下 没找到
我用lol-game-chat这种lcu的接口应该是不行的吧?

然后游戏内又自己单独的剪贴板  我在外面复制的东西在游戏内都无法打出来 
这个也没找到解决方案  求解

**Comment by buffge** [comment]
> > 目前已经发消息给tx lol插件管理员了,我看了一下发消息时橙色风险,应该不违法,如果违法就去掉,tx一周不回复我就把这个功能加进去,默认关闭
> 
> 大佬这个对局内发送消息的代码 大概在什么地方 我找了一下 没找到 我用lol-game-chat这种lcu的接口应该是不行的吧?
> 
> 然后游戏内又自己单独的剪贴板 我在外面复制的东西在游戏内都无法打出来 这个也没找到解决方案 求解

没有接口,需要逆向,我不太确定能不能开源, 怕马哥找我.而且也不知道会不会封号

**Comment by githik999** [comment]
> > > 目前已经发消息给tx lol插件管理员了,我看了一下发消息时橙色风险,应该不违法,如果违法就去掉,tx一周不回复我就把这个功能加进去,默认关闭
> > 
> > 
> > 大佬这个对局内发送消息的代码 大概在什么地方 我找了一下 没找到 我用lol-game-chat这种lcu的接口应该是不行的吧?
> > 然后游戏内又自己单独的剪贴板 我在外面复制的东西在游戏内都无法打出来 这个也没找到解决方案 求解
> 
> 没有接口,需要逆向,我不太确定能不能开源, 怕马哥找我.而且也不知道会不会封号

好的 那我再找找
