### ISSUE TITLE
能否支持macos端

### ISSUE THREAD

**Issue by jqtmviyu** [real-web-world/hh-lol-prophet#35]
macos 下的安装路径是`/Applications/League of Legends.app/Contents/LoL`, opgg, u.gg 等客户端可以检测到战绩. 
但是electron又卡又慢

**Comment by buffge** [comment]
我写代码从不支持苹果,以前写了好几年苹果软件 被折磨怕了.你可以改改 GetLolClientApiInfoV3 这个函数
