### ISSUE TITLE
老哥，请问是怎么监听到对局开始的

### ISSUE THREAD

**Issue by Qiyue0726** [real-web-world/hh-lol-prophet#4]
看不太懂go，好像也没找到相关代码。
那个 ws 我也不太清楚是哪里用的
监听总不能是时刻去请求吧

**Comment by buffge** [comment]
prophet.go 第226 行
	msgType, message, err := c.ReadMessage()

**Comment by Qiyue0726** [comment]
> prophet.go 第226 行 msgType, message, err := c.ReadMessage()

终于连接成功了，谢谢大佬

**Comment by Qiyue0726** [comment]
> prophet.go 第226 行 msgType, message, err := c.ReadMessage()

再问一下，你是怎么知道要发送 `[5, \"OnJsonApiEvent\"]` 这东西给服务器的，我翻了拳头的文档也没找到啊

**Comment by xrr2016** [comment]
> > prophet.go 第226 行 msgType, message, err := c.ReadMessage()
> 
> 再问一下，你是怎么知道要发送 `[5, \"OnJsonApiEvent\"]` 这东西给服务器的，我翻了拳头的文档也没找到啊

https://hextechdocs.dev/getting-started-with-the-lcu-websocket 看这篇文章

**Comment by Qiyue0726** [comment]
> 

居然还有这博客，谢谢了
