### ISSUE TITLE
接受对局接口404

### ISSUE THREAD

**Issue by Dobedoooo** [real-web-world/hh-lol-prophet#6]
<img width="510" alt="uTools_1646563124446" src="https://user-images.githubusercontent.com/57029169/156919571-d0a75014-a474-4f99-9c29-725d12a0c315.png">
但是拒绝接口正常：
<img width="515" alt="uTools_1646563187805" src="https://user-images.githubusercontent.com/57029169/156919608-c4c2f5c4-6857-4cc3-b4c5-47422439e267.png">
但是用您的软件可以正常调用。
我哪里单词写错了吗

**Comment by buffge** [comment]
postman 不支持h2. 用cmd目录下lcu-agent 启动代理 然后请求8098端口即可

**Comment by Dobedoooo** [comment]
解决了，谢谢大佬
