### ISSUE TITLE
大佬问一下进入对局后可以获取到对面人的accountID吗

### ISSUE THREAD

**Issue by githik999** [real-web-world/hh-lol-prophet#8]
可以查对面人的战绩吗?

在选人阶段应该是不行

在进入loading界面或者对局内 可以吗?

我看代码获取自己人的 是通过聊天的

但是游戏内所有人聊天禁止了

**Comment by rainzee** [comment]
可以，对局之后LCU就停止通信了，这个时候可以通过Live Game Data拿到所有Player的信息和ID，然后构造请求去拿对局数据，或者通过WegameApi拿对局数据，我逆向了一部分WegameApi，已经实现了这个功能。

**Comment by githik999** [comment]
> 可以，对局之后LCU就停止通信了，这个时候可以通过Live Game Data拿到所有Player的信息和ID，然后构造请求去拿对局数据，或者通过WegameApi拿对局数据，我逆向了一部分WegameApi，已经实现了这个功能。

牛批  wegame api也是http这样的请求吗

再请教一个问题 在bp阶段 有可能拿到对面人的ID吗?应该不行吧?

**Comment by rainzee** [comment]
BP阶段不行，Wegame的是这样，实际上我已经逆向了Wegame的Api然后实现了一个例子了，在我的仓库里。

**Comment by githik999** [comment]
> BP阶段不行，Wegame的是这样，实际上我已经逆向了Wegame的Api然后实现了一个例子了，在我的仓库里。

okay 我去研究下
